#! /bin/sh
DIR="/opt/chonos-embMAS/lib/SerialPortEmulator/driver/"
MODULE_NAME="virtualbot"
MODULE_FILE="/etc/modules"

if [ "$1" = "start" ]; then
	modprobe $MODULE_NAME
elif [ "$1" = "stop" ]; then
	modprobe -r $MODULE_NAME
elif [ "$1" = "install" ]; then
	cd $DIR
	make clean all
	make modules_install
	make install
	echo $MODULE_NAME >> $MODULE_FILE
elif [ "$1" = "uninstall" ]; then
	cd $DIR
	modprobe -r $MODULE_NAME
	make uninstall
	make clean
	cat $MODULE_FILE | grep -v $MODULE_NAME > /tmp/modules
	mv /tmp/modules $MODULE_FILE
fi
