#! /bin/sh
DIR="/opt/chonos-embMAS/lib/SerialPortEmulator/driver/"

if [ "$1" = "start" ]; then
	modprobe virtualbot
elif [ "$1" = "stop" ]; then
	modprobe -r virtualbot
elif [ "$1" = "install" ]; then
	cd $DIR
	make clean all
	make modules_install
	make install
	echo virtualbot >> /etc/modules
elif [ "$1" = "uninstall" ]; then
	cd $DIR
	modprobe -r virtualbot
	make uninstall
	make clean
	cat /etc/modules | grep -v virtualbot > /tmp/modules
	mv /tmp/modules /etc/modules
fi
